title: "otmnit"
description: "Network, Cloud & Security Engineering Blog"
theme: minima

markdown: kramdown

header_pages:
  - about.md
  - projects.md
  - articles.md
  - posts.md

minima:
  skin: classic

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
  articles:
    output: true

